Restructure docker-sandbox & docker-wine

diff --git a/bin/docker-wine b/bin/docker-wine
--- a/bin/docker-wine
+++ b/bin/docker-wine
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# 32bit/64bit Wine sandbox (no net & x11 default)
+# 32bit/64bit build/run sandboxes (no dri, ipc, net, snd, root & x11 default)
 #
 
 # Locate GIT
@@ -15,22 +15,55 @@ else
     exit 1
 fi
 
-export FLAGS="--volume=$PWD:$PWD --workdir=$PWD --network=none"
+export FLAGS="--network=none"
+export DIST=
+SANDBOX=99999:99999
 while [ $# -gt 0 ]
 do
     case $1 in
+    -dist=*)
+        DIST=`echo "${1#*=}/" | sed -e "s@/@/sandbox/@"`
+        ;;
+    -dri)
+        FLAGS="$FLAGS --device=/dev/dri:/dev/dri"
+        ;;
+    -ipc)
+        FLAGS="$FLAGS --ipc=host"
+        ;;
     -net)
         FLAGS="$FLAGS --network=bridge"
+        ;;
+    -root)
+        SANDBOX="0:0"
+        ;;
+    -snd)
+        FLAGS="$FLAGS --device=/dev/snd:/dev/snd"
+        ;;
+    -user)
+        SANDBOX="$(id -u):$(id -g)"
+        ;;
+    -v=*)
+        MOUNT=${1#*=}
+        FLAGS="$FLAGS --volume=${MOUNT%:ro}:$MOUNT"
         ;;
     -x11)
         FLAGS="$FLAGS --volume=/tmp/.X11-unix:/tmp/.X11-unix --env DISPLAY=$DISPLAY --env XAUTH=\"$(xauth list $DISPLAY)\""
         ;;
     -*)
-        echo "usage: $0 [-net] [-x11] [command]"
+        echo "usage: $0 [-dist=<name>] [-dri] [-net] [-root] [-snd] [-user] [-v=<path>[:ro]] [-x11] [command]"
         echo
         echo "optional arguments:"
-        echo "   -net        Enable network device access."
-        echo "   -x11        Enable X11 display access."
+        ls -1d $DIR/docker/*wine/sandbox/Makefile $DIR/docker/*/sandbox/wine/Makefile 2> /dev/null | \
+            sed -e "s@.*/docker/@@;s@/sandbox@@;s@/Makefile@@" | \
+            awk '{printf("   -dist=%-15s Select sandbox environment.\n", $1)}'
+        echo "   -dri                  Enable direct rendering device access."
+        echo "   -ipc                  Enable shmem for internet process communications."
+        echo "   -net                  Enable network device access."
+        echo "   -root                 Run as root user (Default sandbox user)."
+        echo "   -snd                  Enable sound device access."
+        echo "   -user                 Run as host user & group (Default sandbox user)."
+        echo "   -v=<path>[:ro]        Bind mount a volume (ie \"-v=/path\" & \"-v=/path:ro\")"
+        echo "   -x11                  Enable X11 display access."
         exit 1
         ;;
     *)
@@ -40,19 +73,24 @@ do
     shift
 done
 
-case ${1,,} in
-*.bat|*.cmd)
-    export COMMAND="wine cmd /c $@"
-    ;;
-cmd)
-    export COMMAND="wine cmd"
-    ;;
-*.exe|*.msi)
-    export COMMAND="wine $@"
-    ;;
-*)
-    export COMMAND="$@"
-    ;;
-esac
+# Share current working directory
+FLAGS="$FLAGS --volume=$PWD:/vol/app --workdir=/vol/app"
+
+# Sandbox user
+if [ "$SANDBOX" = "99999:99999" ]
+then
+    FLAGS="$FLAGS --user=$SANDBOX"
+elif [ "$SANDBOX" != "0:0" ]
+then
+    FLAGS="$FLAGS --volume=/etc/passwd:/etc/passwd:ro --volume=/etc/group:/etc/group:ro --user=$SANDBOX"
+fi
+
+export COMMAND="$@"
+
+if [ "$DIST" -a ! -f "$DIR/docker/${DIST}Makefile" ]
+then
+     echo "Error: Cannot locate \"$DIR/docker/${DIST}Makefile\""
+     exit 1
+fi
 
 exec make --quiet -C $DIR/docker run-wine
