Call Python tools directly to remove "module_.py" files

diff --git a/bin/jenkins-jobs b/bin/jenkins-jobs
--- a/bin/jenkins-jobs
+++ b/bin/jenkins-jobs
@@ -1,11 +1,55 @@
 #!/bin/sh
 #
-# Wrapper for Python "bin" script that use package
+# Wrapper for "python"
 #
-VERSION=20160920
+VERSION=20171231
 
-DIR=`dirname "$0"`
-PYTHON="$DIR/python3"
-FILE="$DIR/"`basename "$0" | sed -e "s/-/_/g"`_.py
+. `dirname "$0"`/pyld_mod.sh
 
-exec "$PYTHON" -B "$FILE" "$@"
+PY_MAIN=`basename "$0"`
+case $PY_MAIN in
+python*)
+    PYEXE="$PY_MAIN"
+    ;;
+*)
+    PYEXE=python3
+    ;;
+esac
+
+PYTHON=`locate_python "$@"`
+if [ "$PYTHON" ]
+then
+    if [ "$PYEXE" != "$PY_MAIN" ]
+    then
+        BIN_DIR=`dirname "$PYTHON"`
+        TOOL=`locate_python_tool "$BIN_DIR" "$PY_MAIN"`
+        if [ "$TOOL" ]
+        then
+            exec $PYTHON $TOOL "$@"
+        fi
+    fi
+else
+    PYTHON=`which \`basename "$0"\``
+    if [ ! "$PYTHON" ]
+    then
+        echo "***ERROR*** Cannot find required \"`basename \"$0\"`\" software." 1>&2
+        exit 1
+    fi
+fi
+
+unset PYTHONSTARTUP PYTHONHOME
+if [ ! "`echo \":$PATH:\" | grep \":\`dirname $0\`:\"`" ]
+then
+    PATH=`dirname $0`:$PATH; export PATH
+fi
+
+if [ "$PYEXE" = "$PY_MAIN" ]
+then
+    exec $PYTHON "$@"
+else
+    if [ ! "`which \"$PY_MAIN\"`" ]
+    then
+        echo "***ERROR*** Cannot find required \"$PY_NAME\" software." 1>&2
+    fi
+    exec `which "$PY_MAIN"` "$@"
+fi
